Repository TeamDon-tBe/Don-tBe-iOS, pull requests merged in 2024-03, with the labels that each got.

#158 Feat [#151] 페이지네이션 구현
  DontBe-iOS/DontBe-iOS/Network/Home/DTO/ResponseDTO/PostDataResponseDTO.swift
  DontBe-iOS/DontBe-iOS/Network/Notification/DTO/ResponseDTO/NotificationListResponseDTO.swift
  DontBe-iOS/DontBe-iOS/Network/Post/DTO/ResponseDTO/PostReplyResponseDTO.swift
  DontBe-iOS/DontBe-iOS/Presentation/Home/ViewControllers/HomeViewController.swift
  DontBe-iOS/DontBe-iOS/Presentation/Home/ViewModel/HomeViewModel.swift
  DontBe-iOS/DontBe-iOS/Presentation/MyPage/ViewControllers/MyPageCommentViewController.swift
  DontBe-iOS/DontBe-iOS/Presentation/MyPage/ViewControllers/MyPageContentViewController.swift
  DontBe-iOS/DontBe-iOS/Presentation/MyPage/ViewControllers/MyPageViewController.swift
  DontBe-iOS/DontBe-iOS/Presentation/MyPage/ViewModels/MyPageViewModel.swift
  DontBe-iOS/DontBe-iOS/Presentation/MyPage/Views/MyPageView.swift
  DontBe-iOS/DontBe-iOS/Presentation/Notification/Models/NotificationList.swift
  DontBe-iOS/DontBe-iOS/Presentation/Notification/ViewControllers/NotificationViewController.swift
  DontBe-iOS/DontBe-iOS/Presentation/Notification/ViewModels/NotificationViewModel.swift
  DontBe-iOS/DontBe-iOS/Presentation/Post/ViewControllers/PostDetailViewController.swift
  DontBe-iOS/DontBe-iOS/Presentation/Post/ViewModel/PostDetailViewModel.swift
Labels: Feat, 🐰연수

#159 Fix [#157] 릴리즈 QA 수정사항 1차 반영
  DontBe-iOS/DontBe-iOS/Global/Literals/StringLiterals.swift
  DontBe-iOS/DontBe-iOS/Presentation/MyPage/ViewControllers/MyPageAccountInfoViewController.swift
  DontBe-iOS/DontBe-iOS/Presentation/MyPage/ViewControllers/MyPageEditProfileViewController.swift
  DontBe-iOS/DontBe-iOS/Presentation/MyPage/ViewControllers/MyPageSignOutViewController.swift
  DontBe-iOS/DontBe-iOS/Presentation/MyPage/ViewControllers/MyPageViewController.swift
  DontBe-iOS/DontBe-iOS/Presentation/Post/Cells/PostReplyCollectionViewCell.swift
  DontBe-iOS/DontBe-iOS/Presentation/Post/Views/PostReplyTextFieldView.swift
  DontBe-iOS/DontBe-iOS/Presentation/Post/Views/WriteReplyEditorView.swift
  DontBe-iOS/DontBe-iOS/Presentation/Post/Views/WriteReplyView.swift
  DontBe-iOS/DontBe-iOS/Presentation/Write/ViewControllers/WriteViewController.swift
  DontBe-iOS/DontBe-iOS/Presentation/Write/Views/WriteTextView.swift
  DontBe-iOS/DontBe-iOS/Presentation/Write/Views/WriteView.swift
Labels: 🐢상우, Fix

#161 Feat [#160] 로딩 뷰 구현
  DontBe-iOS/DontBe-iOS.xcodeproj/project.pbxproj
  DontBe-iOS/DontBe-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  DontBe-iOS/DontBe-iOS/Application/AppDelegate.swift
  DontBe-iOS/DontBe-iOS/Global/Literals/StringLiterals.swift
  DontBe-iOS/DontBe-iOS/Global/Resources/loading_yesbe.json
  DontBe-iOS/DontBe-iOS/Presentation/Helpers/DontBeLoadingView.swift
  DontBe-iOS/DontBe-iOS/Presentation/Home/ViewControllers/HomeViewController.swift
Labels: Feat, 🐰연수

#164 Fix [#163] 릴리즈 QA 수정사항 2차 반영
  DontBe-iOS/DontBe-iOS/Global/Literals/StringLiterals.swift
  DontBe-iOS/DontBe-iOS/Global/Resources/Assets.xcassets/etc/title_fourth.imageset/Contents.json
  DontBe-iOS/DontBe-iOS/Global/Resources/Assets.xcassets/etc/title_fourth.imageset/title_four.png
  DontBe-iOS/DontBe-iOS/Global/Resources/Assets.xcassets/etc/title_fourth.imageset/title_four@2x.png
  DontBe-iOS/DontBe-iOS/Global/Resources/Assets.xcassets/etc/title_fourth.imageset/title_four@3x.png
  DontBe-iOS/DontBe-iOS/Global/Resources/Assets.xcassets/etc/title_fourth.imageset/title_fourth.png
  DontBe-iOS/DontBe-iOS/Global/Resources/Assets.xcassets/etc/title_fourth.imageset/title_fourth@2x.png
  DontBe-iOS/DontBe-iOS/Global/Resources/Assets.xcassets/etc/title_fourth.imageset/title_fourth@3x.png
  DontBe-iOS/DontBe-iOS/Network/Post/DTO/ResponseDTO/PostDetailResponseDTO.swift
  DontBe-iOS/DontBe-iOS/Presentation/Home/ViewControllers/HomeViewController.swift
  DontBe-iOS/DontBe-iOS/Presentation/MyPage/ViewControllers/MyPageContentViewController.swift
  DontBe-iOS/DontBe-iOS/Presentation/MyPage/ViewControllers/MyPageViewController.swift
  DontBe-iOS/DontBe-iOS/Presentation/MyPage/Views/MyPageSignOutConfirmView.swift
  DontBe-iOS/DontBe-iOS/Presentation/Post/ViewControllers/PostDetailViewController.swift
  DontBe-iOS/DontBe-iOS/Presentation/Post/ViewControllers/WriteReplyViewController.swift
  DontBe-iOS/DontBe-iOS/Presentation/Post/ViewModel/PostDetailViewModel.swift
  DontBe-iOS/DontBe-iOS/Presentation/Post/Views/PostDetailContentView.swift
  DontBe-iOS/DontBe-iOS/Presentation/Post/Views/WriteReplyContentView.swift
  DontBe-iOS/DontBe-iOS/Presentation/Post/Views/WriteReplyView.swift
Labels: 🐢상우, Fix

#165 Fix [#162] 로딩뷰 수정
  DontBe-iOS/DontBe-iOS/Presentation/Home/ViewControllers/HomeViewController.swift
  DontBe-iOS/DontBe-iOS/Presentation/TabBar/DontBeTabBarController.swift
Labels: Fix, 🐰연수

#167 Fix [#166] 페이징 2개씩 쌓이는 오류사항 해결 완료
  DontBe-iOS/DontBe-iOS/Presentation/Home/ViewModel/HomeViewModel.swift
  DontBe-iOS/DontBe-iOS/Presentation/MyPage/ViewModels/MyPageViewModel.swift
  DontBe-iOS/DontBe-iOS/Presentation/Notification/ViewControllers/NotificationViewController.swift
  DontBe-iOS/DontBe-iOS/Presentation/Post/ViewModel/PostDetailViewModel.swift
Labels: 🐢상우, Fix

#169 Fix [#168] 로딩뷰 QA 이슈 수정
  DontBe-iOS/DontBe-iOS/Global/Literals/StringLiterals.swift
  DontBe-iOS/DontBe-iOS/Presentation/Helpers/DontBeLoadingView.swift
  DontBe-iOS/DontBe-iOS/Presentation/TabBar/DontBeTabBarController.swift
Labels: Fix, 🐰연수

#171 Fix [#170] 카카오 로그인 시, 회원탈퇴 후 재가입 가능한 오류사항 해결
  DontBe-iOS/DontBe-iOS/Presentation/Login/ViewModels/LoginViewModel.swift
Labels: 🐢상우, Fix

#173 Feat [#172] Amplitude Setting 및 적용 완료
  DontBe-iOS/DontBe-iOS.xcodeproj/project.pbxproj
  DontBe-iOS/DontBe-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  DontBe-iOS/DontBe-iOS/Application/AppDelegate.swift
  DontBe-iOS/DontBe-iOS/Global/Resources/Info.plist
  DontBe-iOS/DontBe-iOS/Network/Foundation/Config.swift
  DontBe-iOS/DontBe-iOS/Presentation/Home/ViewModel/HomeViewModel.swift
  DontBe-iOS/DontBe-iOS/Presentation/Join/ViewModels/JoinProfileViewModel.swift
  DontBe-iOS/DontBe-iOS/Presentation/MyPage/ViewModels/MyPageAccountInfoViewModel.swift
  DontBe-iOS/DontBe-iOS/Presentation/Post/ViewModel/PostDetailViewModel.swift
  DontBe-iOS/DontBe-iOS/Presentation/Post/ViewModel/WriteReplyViewModel.swift
  DontBe-iOS/DontBe-iOS/Presentation/Write/ViewModels/WriteViewModel.swift
Labels: 🐢상우, Feat

#175 Fix [#174] 전체적인 페이징 커서 값 오류 해결, 앰플리튜드 오류 해결
  DontBe-iOS/DontBe-iOS/Presentation/Home/ViewControllers/HomeViewController.swift
  DontBe-iOS/DontBe-iOS/Presentation/Home/ViewModel/HomeViewModel.swift
  DontBe-iOS/DontBe-iOS/Presentation/MyPage/ViewControllers/MyPageContentViewController.swift
  DontBe-iOS/DontBe-iOS/Presentation/MyPage/ViewControllers/MyPageViewController.swift
  DontBe-iOS/DontBe-iOS/Presentation/MyPage/ViewModels/MyPageViewModel.swift
  DontBe-iOS/DontBe-iOS/Presentation/Post/ViewControllers/PostDetailViewController.swift
  DontBe-iOS/DontBe-iOS/Presentation/Post/ViewModel/PostDetailViewModel.swift
Labels: 🐢상우, Fix
