Repository TeamDon-tBe/Don-tBe-iOS, pull requests merged in 2024-02, with the labels that each got.

#137 Fix [#130] 프로그레스바 줄어들지 않는 현상, 댓글 순서 변경, 투명도 적용 시 값 전달 변경
  DontBe-iOS/DontBe-iOS/Presentation/Home/ViewControllers/HomeViewController.swift
  DontBe-iOS/DontBe-iOS/Presentation/MyPage/ViewControllers/MyPageCommentViewController.swift
  DontBe-iOS/DontBe-iOS/Presentation/MyPage/ViewControllers/MyPageContentViewController.swift
  DontBe-iOS/DontBe-iOS/Presentation/Post/ViewControllers/PostViewController.swift
  DontBe-iOS/DontBe-iOS/Presentation/Write/Views/WriteTextView.swift
Labels: 🐢상우, Fix

#138 Fix [#133] 필요없는 코드 삭제 및 파일명, 변수명 변경
  DontBe-iOS/DontBe-iOS.xcodeproj/project.pbxproj
  DontBe-iOS/DontBe-iOS/Presentation/Home/Cells/HomeCollectionViewCell.swift
  DontBe-iOS/DontBe-iOS/Presentation/Home/ViewControllers/DeletePopupViewController.swift
  DontBe-iOS/DontBe-iOS/Presentation/Home/ViewControllers/HomeViewController.swift
  DontBe-iOS/DontBe-iOS/Presentation/Home/ViewModel/HomeViewModel.swift
  DontBe-iOS/DontBe-iOS/Presentation/Home/Views/HomeBottomsheetView.swift
  DontBe-iOS/DontBe-iOS/Presentation/Home/Views/HomeCollectionFooterView.swift
  DontBe-iOS/DontBe-iOS/Presentation/Home/Views/HomeCollectionView.swift
  DontBe-iOS/DontBe-iOS/Presentation/Home/Views/HomeView.swift
  DontBe-iOS/DontBe-iOS/Presentation/MyPage/ViewControllers/MyPageCommentViewController.swift
  DontBe-iOS/DontBe-iOS/Presentation/MyPage/ViewControllers/MyPageContentViewController.swift
  DontBe-iOS/DontBe-iOS/Presentation/MyPage/ViewControllers/MyPageViewController.swift
  DontBe-iOS/DontBe-iOS/Presentation/MyPage/Views/MyPageView.swift
  DontBe-iOS/DontBe-iOS/Presentation/Notification/ViewControllers/NotificationViewController.swift
  DontBe-iOS/DontBe-iOS/Presentation/Post/Cells/PostReplyCollectionViewCell.swift
  DontBe-iOS/DontBe-iOS/Presentation/Post/ViewControllers/CancelReplyPopupViewController.swift
  DontBe-iOS/DontBe-iOS/Presentation/Post/ViewControllers/DeleteReplyPopupViewController.swift
  DontBe-iOS/DontBe-iOS/Presentation/Post/ViewControllers/PostDetailViewController.swift
  DontBe-iOS/DontBe-iOS/Presentation/Post/ViewControllers/TransparentPopupViewController.swift
  DontBe-iOS/DontBe-iOS/Presentation/Post/ViewControllers/WriteReplyViewController.swift
  DontBe-iOS/DontBe-iOS/Presentation/Post/ViewModel/PostDetailViewModel.swift
  DontBe-iOS/DontBe-iOS/Presentation/Post/Views/PostDetailCollectionFooterView.swift
  DontBe-iOS/DontBe-iOS/Presentation/Post/Views/PostDetailCollectionHeaderView.swift
  DontBe-iOS/DontBe-iOS/Presentation/Post/Views/PostDetailContentView.swift
  DontBe-iOS/DontBe-iOS/Presentation/Post/Views/PostDetailView.swift
  DontBe-iOS/DontBe-iOS/Presentation/Post/Views/PostPopupView.swift
  DontBe-iOS/DontBe-iOS/Presentation/Post/Views/PostReplyCollectionView.swift
  DontBe-iOS/DontBe-iOS/Presentation/Post/Views/PostReplyTextFieldView.swift
  DontBe-iOS/DontBe-iOS/Presentation/Post/Views/WriteReplyContentView.swift
  DontBe-iOS/DontBe-iOS/Presentation/Post/Views/WriteReplyEditorView.swift
  DontBe-iOS/DontBe-iOS/Presentation/Post/Views/WriteReplyView.swift
Labels: Fix, 🐰연수, Refactor

#141 Feat [#140] 로그아웃, 회원탈퇴 액션 함수 추가
  DontBe-iOS/DontBe-iOS/Global/Literals/ImageLiterals.swift
  DontBe-iOS/DontBe-iOS/Global/Literals/StringLiterals.swift
  DontBe-iOS/DontBe-iOS/Global/Resources/Assets.xcassets/button/btn_logout.imageset/Contents.json
  DontBe-iOS/DontBe-iOS/Global/Resources/Assets.xcassets/button/btn_logout.imageset/btn_logout.png
  DontBe-iOS/DontBe-iOS/Global/Resources/Assets.xcassets/button/btn_logout.imageset/btn_logout@2x.png
  DontBe-iOS/DontBe-iOS/Global/Resources/Assets.xcassets/button/btn_logout.imageset/btn_logout@3x.png
  DontBe-iOS/DontBe-iOS/Network/Foundation/NetworkService.swift
  DontBe-iOS/DontBe-iOS/Presentation/Helpers/DontBeBottomSheetView.swift
  DontBe-iOS/DontBe-iOS/Presentation/MyPage/ViewControllers/MyPageAccountInfoViewController.swift
  DontBe-iOS/DontBe-iOS/Presentation/MyPage/ViewControllers/MyPageViewController.swift
  DontBe-iOS/DontBe-iOS/Presentation/MyPage/Views/MyPageView.swift
Labels: 🐢상우, Feat

#145 Feat [#143] 로그아웃 및 애플로그인 기능 구현
  DontBe-iOS/DontBe-iOS.xcodeproj/project.pbxproj
  DontBe-iOS/DontBe-iOS/Application/AppDelegate.swift
  DontBe-iOS/DontBe-iOS/DontBe-iOS.entitlements
  DontBe-iOS/DontBe-iOS/Network/SocialLogin/DTO/RequestDTO/SocialLoginRequestDTO.swift
  DontBe-iOS/DontBe-iOS/Presentation/Login/ViewControllers/LoginViewController.swift
  DontBe-iOS/DontBe-iOS/Presentation/Login/ViewModels/LoginViewModel.swift
  DontBe-iOS/DontBe-iOS/Presentation/MyPage/ViewControllers/MyPageViewController.swift
Labels: 🍀희주

#146 Feat [#142] 로그아웃, 계정 삭제 팝업 UI 구현
  DontBe-iOS/DontBe-iOS.xcodeproj/project.pbxproj
  DontBe-iOS/DontBe-iOS/Global/Literals/StringLiterals.swift
  DontBe-iOS/DontBe-iOS/Presentation/Helpers/DontBePopupView.swift
  DontBe-iOS/DontBe-iOS/Presentation/MyPage/ViewControllers/MyPageAccountInfoViewController.swift
  DontBe-iOS/DontBe-iOS/Presentation/MyPage/ViewControllers/MyPageSignOutViewController.swift
  DontBe-iOS/DontBe-iOS/Presentation/MyPage/ViewControllers/MyPageViewController.swift
  DontBe-iOS/DontBe-iOS/Presentation/MyPage/Views/MyPageSignOutView.swift
Labels: 🐢상우, Feat

#149 Feat [#148] 게시글 복사 기능 구현
  DontBe-iOS/DontBe-iOS.xcodeproj/project.pbxproj
  DontBe-iOS/DontBe-iOS/Presentation/Helpers/CopyableLabel.swift
  DontBe-iOS/DontBe-iOS/Presentation/Home/Cells/HomeCollectionViewCell.swift
  DontBe-iOS/DontBe-iOS/Presentation/Post/Cells/PostReplyCollectionViewCell.swift
  DontBe-iOS/DontBe-iOS/Presentation/Post/Views/PostDetailCollectionHeaderView.swift
Labels: Feat, 🐰연수

#152 Feat [#150] 프로필 사진 변경 API 연동 및 모든 프로필 사진 부분 적용
  DontBe-iOS/DontBe-iOS.xcodeproj/project.pbxproj
  DontBe-iOS/DontBe-iOS/Application/AppDelegate.swift
  DontBe-iOS/DontBe-iOS/Global/Extension/UIImageView+.swift
  DontBe-iOS/DontBe-iOS/Global/Literals/StringLiterals.swift
  DontBe-iOS/DontBe-iOS/Global/Resources/Info.plist
  DontBe-iOS/DontBe-iOS/Network/UserProfile/DTO/RequestDTO/UserProfileRequestDTO.swift
  DontBe-iOS/DontBe-iOS/Presentation/Helpers/UserInfo.swift
  DontBe-iOS/DontBe-iOS/Presentation/Home/Cells/HomeCollectionViewCell.swift
  DontBe-iOS/DontBe-iOS/Presentation/Home/ViewControllers/HomeViewController.swift
  DontBe-iOS/DontBe-iOS/Presentation/Join/ViewControllers/JoinProfileViewController.swift
  DontBe-iOS/DontBe-iOS/Presentation/Join/ViewModels/JoinProfileViewModel.swift
  DontBe-iOS/DontBe-iOS/Presentation/Join/Views/JoinProfileView.swift
  DontBe-iOS/DontBe-iOS/Presentation/Login/ViewModels/LoginViewModel.swift
  DontBe-iOS/DontBe-iOS/Presentation/MyPage/ViewControllers/MyPageAccountInfoViewController.swift
  DontBe-iOS/DontBe-iOS/Presentation/MyPage/ViewControllers/MyPageCommentViewController.swift
  DontBe-iOS/DontBe-iOS/Presentation/MyPage/ViewControllers/MyPageEditProfileViewController.swift
  DontBe-iOS/DontBe-iOS/Presentation/MyPage/ViewControllers/MyPageViewController.swift
  DontBe-iOS/DontBe-iOS/Presentation/MyPage/ViewModels/MyPageProfileViewModel.swift
  DontBe-iOS/DontBe-iOS/Presentation/MyPage/Views/MyPageNicknameEditView.swift
  DontBe-iOS/DontBe-iOS/Presentation/MyPage/Views/MyPageProfileView.swift
  DontBe-iOS/DontBe-iOS/Presentation/Notification/Cells/NotificationTableViewCell.swift
  DontBe-iOS/DontBe-iOS/Presentation/Onboarding/ViewControllers/OnboardingEndingViewController.swift
  DontBe-iOS/DontBe-iOS/Presentation/Onboarding/ViewModels/OnboardingEndingViewModel.swift
  DontBe-iOS/DontBe-iOS/Presentation/Onboarding/Views/OnboardingEndingView.swift
  DontBe-iOS/DontBe-iOS/Presentation/Post/Cells/PostReplyCollectionViewCell.swift
  DontBe-iOS/DontBe-iOS/Presentation/Post/ViewControllers/PostDetailViewController.swift
  DontBe-iOS/DontBe-iOS/Presentation/Post/ViewControllers/WriteReplyViewController.swift
  DontBe-iOS/DontBe-iOS/Presentation/Post/Views/PostDetailCollectionHeaderView.swift
  DontBe-iOS/DontBe-iOS/Presentation/Post/Views/PostReplyTextFieldView.swift
  DontBe-iOS/DontBe-iOS/Presentation/Post/Views/WriteReplyContentView.swift
  DontBe-iOS/DontBe-iOS/Presentation/Post/Views/WriteReplyEditorView.swift
  DontBe-iOS/DontBe-iOS/Presentation/Write/ViewControllers/WriteViewController.swift
  DontBe-iOS/DontBe-iOS/Presentation/Write/Views/WriteTextView.swift
Labels: 🐢상우, Feat, Network

#154 Feat [#153] 투명도 기능 버전2 적용, API 연동 구현
  DontBe-iOS/DontBe-iOS.xcodeproj/project.pbxproj
  DontBe-iOS/DontBe-iOS/Global/Literals/ImageLiterals.swift
  DontBe-iOS/DontBe-iOS/Global/Resources/Assets.xcassets/button/btn_radio.imageset/Contents.json
  DontBe-iOS/DontBe-iOS/Global/Resources/Assets.xcassets/button/btn_radio.imageset/btn_radio.png
  DontBe-iOS/DontBe-iOS/Global/Resources/Assets.xcassets/button/btn_radio.imageset/btn_radio@2x.png
  DontBe-iOS/DontBe-iOS/Global/Resources/Assets.xcassets/button/btn_radio.imageset/btn_radio@3x.png
  DontBe-iOS/DontBe-iOS/Global/Resources/Assets.xcassets/button/btn_radio_selected.imageset/Contents.json
  DontBe-iOS/DontBe-iOS/Global/Resources/Assets.xcassets/button/btn_radio_selected.imageset/btn_radio_selected.png
  DontBe-iOS/DontBe-iOS/Global/Resources/Assets.xcassets/button/btn_radio_selected.imageset/btn_radio_selected@2x.png
  DontBe-iOS/DontBe-iOS/Global/Resources/Assets.xcassets/button/btn_radio_selected.imageset/btn_radio_selected@3x.png
  DontBe-iOS/DontBe-iOS/Network/Transparency/RequestDTO/PostTransparencyRequestDTO.swift
  DontBe-iOS/DontBe-iOS/Presentation/Helpers/DontBePopupReasonListCustomView.swift
  DontBe-iOS/DontBe-iOS/Presentation/Helpers/DontBePopupReasonView.swift
  DontBe-iOS/DontBe-iOS/Presentation/Home/ViewControllers/HomeViewController.swift
  DontBe-iOS/DontBe-iOS/Presentation/Home/ViewModel/HomeViewModel.swift
  DontBe-iOS/DontBe-iOS/Presentation/MyPage/ViewControllers/MyPageCommentViewController.swift
  DontBe-iOS/DontBe-iOS/Presentation/MyPage/ViewControllers/MyPageContentViewController.swift
  DontBe-iOS/DontBe-iOS/Presentation/MyPage/ViewControllers/MyPageViewController.swift
  DontBe-iOS/DontBe-iOS/Presentation/Post/ViewControllers/PostDetailViewController.swift
  DontBe-iOS/DontBe-iOS/Presentation/Post/ViewModel/PostDetailViewModel.swift
Labels: 🐢상우, Feat, Network
